name: PayRespects
main: blfngl.pay_respects.PayRespects
version: 0.8
author: blfngl. John_Smith
commands:
    f:
        description: Pay your respects.
        usage: /f [player]
        permission: payrespects.f
        permission-message: You can't pay your respects.
    fhelp:
        description: PayRespects information.
        usage: fhelp
        permission: payrespects.finfo
        permission-message: You can't help your respects.
    fdebug:
        description: Toggles PayRespects debugging mode.
        usage: /fdebug
        permission: payrespects.fdebug
        permission-message: You can't debug your respects.
    fset:
        description: Change the values of the respect window or payment amount.
        usage: /fset <window/payment> [integer]
        permission: payrespects.fset
        permission-message: You can't change your respect amounts.
    ftoggleheader:
        description: Toggles the PayRespects text header on or off.
        usage: /ftoggleheader
        permission: payrespects.ftoggleheader
        permission-message: You can't toggle your respect header.
    x:
        description: Doubt.
        usage: /x
        permission: payrespects.x
        permission-message: [Intelligence 4/9]
    xtoggle:
        description: Toggles only doubt mode on or off.
        usage: /xtoggle
        permission: payrespects.xtoggle
        permission-message: You're doubting your decision.

permissions:
    payrespects.*:
        description: Gives access to all PayRespects commands.
        children:
            payrespects.f: true
            payrespects.fhelp: true
            payrespects.fdebug: true
            payrespects.fset: true
            payrespects.ftoggleheader: true
            payrespects.x: true
            payrespects.xtoggle: true
    payrespects.f:
        default: true
    payrespects.fhelp:
        default: true
    payrespects.fdebug:
        default: op
    payrespects.fset:
        default: op
    payrespects.ftoggleheader:
        default: op
    payrespects.x:
        default: true
    payrespects.xtoggle:
        default: op