name: PayRespects
main: blfngl.pay_respects.PayRespects
version: 0.8
author: blfngl. John_Smith
commands:
    f:
        description: Pay your respects.
        usage: /f [player]
        permission: payrespects.f
        permission-message: You can't pay your respects.
    fhelp:
        description: PayRespects information.
        usage: fhelp
        permission: payrespects.finfo
        permission-message: You can't help your respects.
    fdebug:
        description: Toggles PayRespects debugging mode.
        usage: /fdebug
        permission: payrespects.fdebug
        permission-message: You can't debug your respects.
    fset:
        description: Change the values of the respect window or payment amount.
        usage: /fset <window/payment> [integer]
        permission: payrespects.fset
        permission-message: You can't change your respect amounts.
    ftoggle:
        description: Toggles the PayRespects text header on or off.
        usage: /ftoggle
        permission: payrespects.ftoggle
        permission-message: You can't toggle your respect header.

permissions:
    payrespects.*:
        description: Gives access to all PayRespects commands.
        children:
            payrespects.f: true
            payrespects.fhelp: true
            payrespects.fdebug: true
            payrespects.fset: true
            payrespects.ftoggle: true
    payrespects.f:
        default: true
    payrespects.fhelp:
        default: true
    payrespects.fdebug:
        default: op
    payrespects.fset:
        default: op
    payrespects.ftoggle:
        default: op
